<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <UnoSingleProject>true</UnoSingleProject>
    <OutputType>Library</OutputType>
    <!-- Ensures the .xr.xml files are generated in a proper layout folder -->
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Enables Uno XAML codegen and build logic -->
    <UseUnoXaml>true</UseUnoXaml>
    <EnableDefaultXamlItems>true</EnableDefaultXamlItems>
    <AssemblyVersion>1.2.0</AssemblyVersion>
    <FileVersion>1.2.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Scrubbler.PluginBase" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Scrubbler.Test.FileParseScrobblerTest</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Update="FileParseScrobbleView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Parser\CSV\CsvFileParserConfigurationEditView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Parser\CSV\CsvFileParserConfigurationEditView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="FileParseScrobbleView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Parser\JSON\JsonFileParserConfigurationEditView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>