<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net10.0-desktop;net10.0</TargetFrameworks>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>

        <UnoFeatures>
            Material;
            Hosting;
            Toolkit;
            Logging;
            Mvvm;
            Configuration;
            Navigation;
            ThemeService;
            SkiaRenderer;
        </UnoFeatures>

        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
        <!-- Metadata -->
        <ApplicationTitle>Scrubbler 2</ApplicationTitle>
        <ApplicationId>Scrubbler.Host</ApplicationId>
        <ApplicationDisplayVersion>0.0.1</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationPublisher>SHOEGAZEssb</ApplicationPublisher>
        <Description>Scrubbler 2 - Manual scrobbling for when a service (or you!) failed to scrobble.</Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Scrubbler.Test" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Presentation\Controls\**" />
        <EmbeddedResource Remove="Presentation\Controls\**" />
        <None Remove="Presentation\Controls\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets\noartistimage.png" />
    </ItemGroup>

    <!-- XAML pages -->
    <ItemGroup>
        <!-- App.xaml must be ApplicationDefinition so Main() gets generated -->
        <ApplicationDefinition Include="App.xaml" />

        <!-- Regular pages / usercontrols -->
        <Page Include="Presentation\MainPage.xaml" />
        <Page Include="Presentation\Shell.xaml" />
        <Page Include="Presentation\Accounts\AccountsView.xaml" />
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Logging\LogView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\InstalledPluginsView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\PluginManagerView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\AvailablePluginsView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Presentation\Plugins\ScrobblePluginHostView.xaml.cs">
            <DependentUpon>ScrobblePluginHostView.xaml</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\ScrobblePluginHostView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\ScrobblePreviewDialog.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Page Update="Presentation\Plugins\AutoScrobblePluginHostView.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>
    <ItemGroup>
        <Content Remove="Presentation\Controls\**" />
    </ItemGroup>
    <ItemGroup>
        <Page Remove="Presentation\Controls\**" />
    </ItemGroup>
    <ItemGroup>
        <UpToDateCheckInput Remove="Presentation\Controls\**" />
    </ItemGroup>
    <ItemGroup>
        <PRIResource Remove="Presentation\Controls\**" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.WinUI.Managed" />
        <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI" />
        <PackageReference Include="CommunityToolkit.WinUI.Extensions" />
        <PackageReference Include="DiscordRichPresence" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="SkiaSharp" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Plugins\Scrubbler.PluginBase\Scrubbler.PluginBase.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Page Update="Presentation\HomeView.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Presentation\Settings\SettingsView.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Presentation\Settings\UpdateDialog.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Presentation\Settings\UpdateInProgressDialog.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
    <ItemGroup>
      <Page Update="Presentation\Settings\AboutSettingsCategoryView.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>
</Project>
