<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UnoSingleProject>true</UnoSingleProject>
    <OutputType>Library</OutputType>
    <!-- Ensures the .xr.xml files are generated in a proper layout folder -->
    <GenerateLibraryLayout>true</GenerateLibraryLayout>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- Enables Uno XAML codegen and build logic -->
    <UseUnoXaml>true</UseUnoXaml>
    <EnableDefaultXamlItems>true</EnableDefaultXamlItems>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FlaUI.UIA3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scrubbler.MediaPlayerScrobblerBase\Scrubbler.MediaPlayerScrobblerBase.csproj" />
    <ProjectReference Include="..\Scrubbler.PluginBase\Scrubbler.PluginBase.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Scrubbler.Test.AppleMusicScrobblerTest</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Update="AppleMusicScrobbleView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="environment.env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Page Update="AppleMusicScrobbleView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Content Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
