<Project Sdk="Uno.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.1.0</AssemblyVersion>
    <FileVersion>1.1.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scrubbler.PluginBase" />
    <PackageReference Include="Shoegaze.LastFM" />
  </ItemGroup>

  <ItemGroup>
    <None Update="environment.env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Content Include="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LastFmAccountPlugin.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
</Project>
